---
# tasks file for kushwiz.mongodb

- group: name={{mongodb_group}} state=present
- user: name={{mongodb_user}} uid=1040 group={{mongodb_group}}

- apt: update_cache=yes
- apt: name=numactl state=latest
- apt: name=python-pip state=latest
- pip: name=pymongo state=latest

- name: Is MongoDB already available?
  stat: path=/opt/{{mongodb_directory}}.tgz
  register: mongodb_archive_stat

- name: download MongoDB
  get_url: url={{mongodb_download_url}} dest=/opt mode=0440
  when: mongodb_archive_stat.stat.isreg is not defined

- name: extract archive
  unarchive: src=/opt/{{mongodb_directory}}.tgz dest=/opt copy=no

- name: symlink directory
  file: src=/opt/{{mongodb_directory}} dest=/opt/mongodb state=link

- name: Create the conf file
  template: src=mongod_conf.j2 dest={{mongodb_config_path}} mode=0655

- name: Create the init script
  template: src=init_mongo.j2 dest=/etc/init.d/mongodb mode=0655

- name: Copying keyfile
  template: src=mongod_keyfile.j2 dest=/opt/mongodb/keyfile mode=0700 owner={{mongodb_user}} group={{mongodb_group}}

- name: Create db directory
  file: path={{mongodb_datadir_prefix}} state=directory mode=0755 owner={{mongodb_user}} group={{mongodb_group}}
  sudo: yes

- name: Create log directory
  file: path={{mongodb_log_path}} state=directory mode=0755 owner={{mongodb_user}} group={{mongodb_group}}
  sudo: yes

- name: Starting up MongoDB
  service: name=mongodb state=started
  sudo: yes

- name: Create admin user
  mongodb_user: database=admin name={{mongodb_admin_user}} password={{mongodb_admin_pass}} state=present roles="dbAdmin" login_port={{mongodb_port}}
